version: "3.9"

services:
  backend:
    build:
      dockerfile: ./backend.Dockerfile
      context: .
      args:
        # Valid model values: tiny, base, small, medium, large
        - WHISPER_MODEL=small
        - WHISPER_THREADS=4 # Number of threads to use during computation
        - WHISPER_PROCESSORS=1 # Number of processors to use during computation
        - CUT_MEDIA_SECONDS=10
    container_name: web-whisper-backend
  
  whisper:
    build:
      dockerfile: ./frontend.Dockerfile
      context: .
      args:
        - DOMAIN_NAME=http://localhost:3000 # Make sure to add the correct protocol (http/https)
        - ALLOW_FILE_UPLOADS=true
    container_name: web-whisper
    ports:
      - "127.0.0.1:3000:80"